__version__ = "0.4.2"
__author__ = "Nico Schlömer"
__author_email__ = "nico.schloemer@gmail.com"
__website__ = "https://github.com/nschloe/dedec"
__license__ = "License :: OSI Approved :: MIT License"
__status__ = "Development Status :: 4 - Beta"
