#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
import argparse
import decimal2rational

if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        description='Convert decimal to (approximate) rational number.'
        )
    parser.add_argument(
            'decimal',
            type=float,
            help='input decimal number'
            )
    parser.add_argument(
            '--tolerance', '-t',
            type=float,
            default=1.0e-10,
            help='relative tolerance'
            )
    parser.add_argument(
            '--max-denominator', '-m',
            type=int,
            default=1000,
            help='maximum denominator to check'
            )
    parser.add_argument(
            '--max-root', '-r',
            type=int,
            default=5,
            help='maximum denominator to check'
            )

    args = parser.parse_args()

    num, denom, root, diff = decimal2rational.decimal2rational(
            args.decimal,
            tol=args.tolerance,
            max_denominator=args.max_denominator,
            max_root=args.max_root
            )

    if num is None:
        print('No rational number found that approximates %r well enough.' %
              args.decimal
              )
    elif root == 1:
        print('%r = %d / %d   %+0.4e' % (args.decimal, num, denom, diff))
    elif root == 2:
        print('%r = sqrt(%d / %d)   %+0.4e' % (args.decimal, num, denom, diff))
    else:
        print('%r = (%d / %d)^(1/%d)   %+0.4e' %
              (args.decimal, num, denom, root, diff)
              )
