#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
import argparse
import decimal2rational

if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        description='Convert decimal to (approximate) rational number.'
        )
    parser.add_argument(
            'decimal',
            type=float,
            help='input decimal number'
            )
    parser.add_argument(
            '--tolerance', '-t',
            type=float,
            default=1.0e-5,
            help='relative tolerance'
            )
    parser.add_argument(
            '--max-denominator', '-m',
            type=int,
            default=1000,
            help='maximum denominator to check'
            )

    args = parser.parse_args()

    sols = decimal2rational.decimal2rational(
            args.decimal,
            tol=args.tolerance,
            max_denominator=args.max_denominator
            )

    # num, denom, mult_pi, fun_name, diff = decimal2rational.decimal2rational(

    if len(sols) == 0:
        print('No expression found that approximates %r well enough.' %
              args.decimal
              )
    else:
        sols.sort(key=lambda x: abs(x[4]))
        for sol in sols:
            num, denom, mult_pi, fun_name, diff = sol

            print('%s   %+0.4e' % (
                decimal2rational.repr(num, denom, mult_pi, fun_name),
                diff
                ))
